Plataforma/config/routes.rb
Rails.application.routes.draw do

  get 'med/calcular'
  get 'med/show'

  resources :epiyears do
    collection { post :import }
  end
  
  resources :geo_positions

  resources :zones do
    collection { post :import }
  end
  resources :events do
    collection { post :import }
  end

  resources :permissions
  resources :roles
  resources :faqs
  devise_for :users
  resources :equipos
  
  get 'static_pages/home'
  get 'static_pages/publicaciones'
  get 'static_pages/contacto'

  root 'static_pages#home'

end

Plataforma/app/models/geo_position.rb
class GeoPosition < ActiveRecord::Base
  belongs_to :zone
end

Plataforma/app/controllers/geo_positions_controller.rb
class GeoPositionsController < ApplicationController
  before_action :set_geo_position, only: [:show, :edit, :update, :destroy]

  # GET /geo_positions
  # GET /geo_positions.json
  def index
    @geo_positions = GeoPosition.all
  end

  # GET /geo_positions/1
  # GET /geo_positions/1.json
  def show
  end

  # GET /geo_positions/new
  def new
    @geo_position = GeoPosition.new
  end

  # GET /geo_positions/1/edit
  def edit
  end

  # POST /geo_positions
  # POST /geo_positions.json
  def create
    @geo_position = GeoPosition.new(geo_position_params)

    respond_to do |format|
      if @geo_position.save
        format.html { redirect_to @geo_position, notice: 'Geo position was successfully created.' }
        format.json { render :show, status: :created, location: @geo_position }
      else
        format.html { render :new }
        format.json { render json: @geo_position.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /geo_positions/1
  # PATCH/PUT /geo_positions/1.json
  def update
    respond_to do |format|
      if @geo_position.update(geo_position_params)
        format.html { redirect_to @geo_position, notice: 'Geo position was successfully updated.' }
        format.json { render :show, status: :ok, location: @geo_position }
      else
        format.html { render :edit }
        format.json { render json: @geo_position.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /geo_positions/1
  # DELETE /geo_positions/1.json
  def destroy
    @geo_position.destroy
    respond_to do |format|
      format.html { redirect_to geo_positions_url, notice: 'Geo position was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_geo_position
      @geo_position = GeoPosition.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def geo_position_params
      params.require(:geo_position).permit(:lat, :lng, :zone_id)
    end
end

Plataforma/app/helpers/geo_positions_helper.rb
module GeoPositionsHelper
end

Plataforma/app/views/geo_positions/_form.html.erb
<%= form_for(@geo_position) do |f| %>
  <% if @geo_position.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@geo_position.errors.count, "error") %> prohibited this geo_position from being saved:</h2>

      <ul>
      <% @geo_position.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :lat %><br>
    <%= f.text_field :lat %>
  </div>
  <div class="field">
    <%= f.label :lng %><br>
    <%= f.text_field :lng %>
  </div>
  <div class="field">
    <%= f.label :zone_id %><br>
    <%= f.number_field :zone_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

Plataforma/app/views/geo_positions/edit.html.erb
<h1>Editing Geo Position</h1>

<%= render 'form' %>

<%= link_to 'Show', @geo_position %> |
<%= link_to 'Back', geo_positions_path %>

Plataforma/app/views/geo_positions/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Geo Positions</h1>

<table>
  <thead>
    <tr>
      <th>Lat</th>
      <th>Lng</th>
      <th>Zone</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @geo_positions.each do |geo_position| %>
      <tr>
        <td><%= geo_position.lat %></td>
        <td><%= geo_position.lng %></td>
        <td><%= geo_position.zone_id %></td>
        <td><%= link_to 'Show', geo_position %></td>
        <td><%= link_to 'Edit', edit_geo_position_path(geo_position) %></td>
        <td><%= link_to 'Destroy', geo_position, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Geo position', new_geo_position_path %>

Plataforma/app/views/geo_positions/new.html.erb
<h1>New Geo Position</h1>

<%= render 'form' %>

<%= link_to 'Back', geo_positions_path %>

Plataforma/app/views/geo_positions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Lat:</strong>
  <%= @geo_position.lat %>
</p>

<p>
  <strong>Lng:</strong>
  <%= @geo_position.lng %>
</p>

<p>
  <strong>Zone:</strong>
  <%= @geo_position.zone_id %>
</p>

<%= link_to 'Edit', edit_geo_position_path(@geo_position) %> |
<%= link_to 'Back', geo_positions_path %>