Plataforma/config/routes.rb
Rails.application.routes.draw do

  get 'med/calcular'
  get 'med/show'

  resources :epiyears do
    collection { post :import }
  end
  
  resources :geo_positions

  resources :zones do
    collection { post :import }
  end
  resources :events do
    collection { post :import }
  end

  resources :permissions
  resources :roles
  resources :faqs
  devise_for :users
  resources :equipos
  
  get 'static_pages/home'
  get 'static_pages/publicaciones'
  get 'static_pages/contacto'

  root 'static_pages#home'

end

Plataforma/app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
      user ||= User.new # guest user (not logged in)
      if user.role == "admin"
        alias_action :create, :read, :update, :destroy, :to => :crud

        can :crud, :all
        can :manage, :all
        can :update, :all
      else
        can :read, :all
      end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

Plataforma/app/models/epiyear.rb
class Epiyear < ActiveRecord::Base

	def self.import(file)
	  spreadsheet = open_spreadsheet(file)
	  header = spreadsheet.row(1)
	  (2..spreadsheet.last_row).each do |i|
	    row = Hash[[header, spreadsheet.row(i)].transpose]
	    epiyear = find_by_id(row["id"]) || new
	    epiyear.attributes = row.to_hash.slice(*Epiyear.attribute_names())
	    epiyear.save!
	  end
	end

	def self.open_spreadsheet(file)
	  case File.extname(file.original_filename)
	  when ".csv" then Roo::Csv.new(file.path)
	  when ".xls" then Roo::Excel.new(file.path)
	  when ".xlsx" then Roo::Excelx.new(file.path)
	  else raise "Unknown file type: #{file.original_filename}"
	  end
	end
end

Plataforma/app/models/equipo.rb
class Equipo < ActiveRecord::Base
	# mount_uploader :foto, fotoUploader
end

Plataforma/app/models/event.rb
require 'roo-xls'

class Event < ActiveRecord::Base

  def self.to_csv(options = {})
    CSV.generate(options) do |csv|
      csv << column_names
      all.each do |event|
        csv << event.attributes.values_at(*column_names)
      end
    end
  end

  def self.import(file)
    spreadsheet = open_spreadsheet(file)
    header = spreadsheet.row(1)
    (2..spreadsheet.last_row).each do |i|
      row = Hash[[header, spreadsheet.row(i)].transpose]
      product = find_by_id(row["id"]) || new
      product.attributes = row.to_hash.slice(*Event.attribute_names())
      product.save!
    end
  end

    def self.open_spreadsheet(file)
      case File.extname(file.original_filename)
      when ".csv" then Roo::Csv.new(file.path)
      when ".xls" then Roo::Excel.new(file.path)
      when ".xlsx" then Roo::Excelx.new(file.path)
      else raise "Unknown file type: #{file.original_filename}"
    end
  end
end

Plataforma/app/models/faq.rb
class Faq < ActiveRecord::Base
end

Plataforma/app/models/geo_position.rb
class GeoPosition < ActiveRecord::Base
  belongs_to :zone
end

Plataforma/app/models/permission.rb
class Permission < ActiveRecord::Base
end

Plataforma/app/models/role.rb
class Role < ActiveRecord::Base
	has_many :permissions
 	has_many :users, :through => :permissions

 	def admin?(role)
 		role.eql?("admin")
 	end
end

Plataforma/app/models/user.rb
class User < ActiveRecord::Base

  attr_accessor :role	

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :permissions
  has_many :roles, :through => :permissions

end

Plataforma/app/models/zone.rb
class Zone < ActiveRecord::Base
  has_many :geoPositions
  accepts_nested_attributes_for :geoPositions,allow_destroy: true

  def self.import(file)
    spreadsheet = open_spreadsheet(file)
    spreadsheet.each_with_pagename do |name, sheet|
      header = sheet.row(1)
      zone 
      (2..spreadsheet.last_row).each do |i|
        row = Hash[[header, spreadsheet.row(i)].transpose]
        geoPositions = find_by_id(row["id"]) || new
        zone.attributes = row.to_hash.slice(*Zone.attribute_names(), name)
        zone.save!
      end
    end
  end

  def self.open_spreadsheet(file)
    case File.extname(file.original_filename)
      #when ".csv" then Csv.new(file.path, nil, :ignore)
      when ".xls" then Roo::Excel.new(file.path)
      when ".xlsx" then Roo::Excelx.new(file.path)
      else raise "Unknown file type: #{file.original_filename}"
    end
  end
end

Plataforma/app/controllers/med_controller.rb
class MedController < ApplicationController
  def calcular
  end

  def show
#  	@a = params[:all]
  	@value = %x(python Curva.py #{params[:a]} #{params[:b]} #{params[:c]} #{params[:d]} #{params[:e]} #{params[:f]} #{params[:g]} #{params[:h]} #{params[:i]} #{params[:j]})
  	
  end
end

Plataforma/app/helpers/application_helper.rb
module ApplicationHelper
  # Methods for add and remove dinamically fields, see inovices :)
def link_to_remove_fields(name, f)
  f.hidden_field(:_destroy) + link_to(name, "#",:class => "remove_link_class")
end

def link_to_add_fields(name, f, association)
=begin
  new_object = f.object.class.reflect_on_association(association).klass.new
  fields = f.fields_for(association, new_object, :child_index => "new_#{association}") do |builder|
    render(association.to_s.singularize + "_fields", :f => builder)
  end
  link_to(name,'#', :onclick=>"add_fields(this, \"#{association}\", \"#{escape_javascript(fields)}\")")
=end
  new_object = f.object.send(association).klass.new
   id = new_object.object_id
   fields = f.fields_for(association, new_object, child_index: id) do |builder|
     render(association.to_s.singularize + "_fields", f: builder)
   end
   link_to(name, '#', class: "add_fields", data: {id: id, fields: fields.gsub("\n", "")})

end

end

Plataforma/app/helpers/epiyears_helper.rb
module EpiyearsHelper
end

Plataforma/app/helpers/equipos_helper.rb
module EquiposHelper
end

Plataforma/app/helpers/events_helper.rb
module EventsHelper
end

Plataforma/app/helpers/faqs_helper.rb
module FaqsHelper
end

Plataforma/app/helpers/med_helper.rb
module MedHelper
end

Plataforma/app/helpers/permissions_helper.rb
module PermissionsHelper
end

Plataforma/app/helpers/roles_helper.rb
module RolesHelper
end

Plataforma/app/helpers/zones_helper.rb
module ZonesHelper
  def getGeoPositions(zone)
    zone.geoPositions
  end
end

Plataforma/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><%= content_for?(:title) ? yield(:title) : "Predicción Dengue" %></title>

    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "vendor/modernizr" %>
    <%= javascript_include_tag "application", 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>

  <body>
   <nav class="top-bar" data-topbar role="navigation">
    <ul class="title-area">
      <li class="name"> <h1><%= link_to 'Home', root_path %></a></h1></li>
      <!-- Remove the class "menu-icon" to get rid of menu icon. Take out "Menu" to just have icon alone -->
      <li class="toggle-topbar menu-icon"><a href="#"><span>Menu</span></a></li>
    </ul>


    <section class="top-bar-section">
      <ul class="right">
        <li ><a href="#">Contacto</a></li>
        <li class="has-dropdown">
          <a href="#"> Usuarios </a>
            <ul class="dropdown">
              <% if user_signed_in? %> Logged in as <strong> <%= current_user.email %> </strong>.</a> </li>
              <li> <a href="#"> <%= link_to 'Edit profile', edit_user_registration_path %> </a></li>
              <li> <a href="#"> <%= link_to "Logout", destroy_user_session_path, method: :delete %> </a></li>
              <% else %>
              <li> <a href="#"> <%= link_to "Sign up", new_user_registration_path %></a></li>
              <li> <a href="#"> <%= link_to "Login", new_user_session_path %> </a></li>
              <% end %>
          </ul>
      </ul>

      <!-- Left Nav Section -->
      <ul class="left">
        <li><a href="#"><%= link_to 'Nuestro Equipo', equipos_path %></a></li>
        <li><a href="#">Publicaciones</a></li>
        <li><a href="#">Progreso</a></li>
        <li><a href="#">Proyectos</a></li>
        <li><a href="#"></a> <%= link_to "FAQs", faqs_path %> </li>
        <li><a href="#"></a> <%= link_to "Epi Year", epiyears_path %> </li>
        <li><a href="#"></a> <%= link_to "Casos", events_path %> </li>
        <li><a href="#"></a> <%= link_to "MED", med_calcular_path %> </li>
      </ul>       

    </section>
    </nav>

      <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>
   

      <%= yield %>

    </div>
  </body>
</html>