Plataforma/config/routes.rb
Rails.application.routes.draw do

  get 'med/calcular'
  get 'med/show'

  resources :epiyears do
    collection { post :import }
  end
  
  resources :geo_positions

  resources :zones do
    collection { post :import }
  end
  resources :events do
    collection { post :import }
  end

  resources :permissions
  resources :roles
  resources :faqs
  devise_for :users
  resources :equipos
  
  get 'static_pages/home'
  get 'static_pages/publicaciones'
  get 'static_pages/contacto'

  root 'static_pages#home'

end

Plataforma/app/models/epiyear.rb
class Epiyear < ActiveRecord::Base

	def self.import(file)
	  spreadsheet = open_spreadsheet(file)
	  header = spreadsheet.row(1)
	  (2..spreadsheet.last_row).each do |i|
	    row = Hash[[header, spreadsheet.row(i)].transpose]
	    epiyear = find_by_id(row["id"]) || new
	    epiyear.attributes = row.to_hash.slice(*Epiyear.attribute_names())
	    epiyear.save!
	  end
	end

	def self.open_spreadsheet(file)
	  case File.extname(file.original_filename)
	  when ".csv" then Roo::Csv.new(file.path)
	  when ".xls" then Roo::Excel.new(file.path)
	  when ".xlsx" then Roo::Excelx.new(file.path)
	  else raise "Unknown file type: #{file.original_filename}"
	  end
	end
end

Plataforma/app/controllers/epiyears_controller.rb
class EpiyearsController < ApplicationController
  before_action :set_epiyear, only: [:show, :edit, :update, :destroy]


  def import
    Epiyear.import(params[:file])
    redirect_to epiyears_url, notice: "Datos Importados."
  end

  # GET /epiyears
  # GET /epiyears.json
  def index
    @epiyears = Epiyear.all
  end

  # GET /epiyears/1
  # GET /epiyears/1.json
  def show
  end

  # GET /epiyears/new
  def new
    @epiyear = Epiyear.new
  end

  # GET /epiyears/1/edit
  def edit
  end

  # POST /epiyears
  # POST /epiyears.json
  def create
    @epiyear = Epiyear.new(epiyear_params)

    respond_to do |format|
      if @epiyear.save
        format.html { redirect_to @epiyear, notice: 'Epiyear was successfully created.' }
        format.json { render :show, status: :created, location: @epiyear }
      else
        format.html { render :new }
        format.json { render json: @epiyear.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /epiyears/1
  # PATCH/PUT /epiyears/1.json
  def update
    respond_to do |format|
      if @epiyear.update(epiyear_params)
        format.html { redirect_to @epiyear, notice: 'Epiyear was successfully updated.' }
        format.json { render :show, status: :ok, location: @epiyear }
      else
        format.html { render :edit }
        format.json { render json: @epiyear.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /epiyears/1
  # DELETE /epiyears/1.json
  def destroy
    @epiyear.destroy
    respond_to do |format|
      format.html { redirect_to epiyears_url, notice: 'Epiyear was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_epiyear
      @epiyear = Epiyear.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def epiyear_params
      params.require(:epiyear).permit(:year, :s1, :s2, :s3, :s4, :s5, :s6, :s7, :s8, :s9, :s10, :s11, :s12, :s13, :s14, :s15, :s16, :s17, :s18, :s19, :s20, :s21, :s22, :s23, :s24, :s25, :s26, :s27, :s28, :s29, :s30, :s31, :s32, :s33, :s34, :s35, :s36, :s37, :s38, :s39, :s40, :s41, :s42, :s43, :s44, :s45, :s46, :s47, :s48, :s49, :s50, :s51, :s52, :poblacion)
    end
end

Plataforma/app/helpers/epiyears_helper.rb
module EpiyearsHelper
end

Plataforma/app/views/epiyears/_form.html.erb
<%= form_for(@epiyear) do |f| %>
  <% if @epiyear.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@epiyear.errors.count, "error") %> prohibited this epiyear from being saved:</h2>

      <ul>
      <% @epiyear.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :Año %><br>
    <%= f.number_field :year %>
  </div>
  <div class="field">
    <%= f.label :s1 %><br>
    <%= f.number_field :s1 %>
  </div>
  <div class="field">
    <%= f.label :s2 %><br>
    <%= f.number_field :s2 %>
  </div>
  <div class="field">
    <%= f.label :s3 %><br>
    <%= f.number_field :s3 %>
  </div>
  <div class="field">
    <%= f.label :s4 %><br>
    <%= f.number_field :s4 %>
  </div>
  <div class="field">
    <%= f.label :s5 %><br>
    <%= f.number_field :s5 %>
  </div>
  <div class="field">
    <%= f.label :s6 %><br>
    <%= f.number_field :s6 %>
  </div>
  <div class="field">
    <%= f.label :s7 %><br>
    <%= f.number_field :s7 %>
  </div>
  <div class="field">
    <%= f.label :s8 %><br>
    <%= f.number_field :s8 %>
  </div>
  <div class="field">
    <%= f.label :s9 %><br>
    <%= f.number_field :s9 %>
  </div>
  <div class="field">
    <%= f.label :s10 %><br>
    <%= f.number_field :s10 %>
  </div>
  <div class="field">
    <%= f.label :s11 %><br>
    <%= f.number_field :s11 %>
  </div>
  <div class="field">
    <%= f.label :s12 %><br>
    <%= f.number_field :s12 %>
  </div>
  <div class="field">
    <%= f.label :s13 %><br>
    <%= f.number_field :s13 %>
  </div>
  <div class="field">
    <%= f.label :s14 %><br>
    <%= f.number_field :s14 %>
  </div>
  <div class="field">
    <%= f.label :s15 %><br>
    <%= f.number_field :s15 %>
  </div>
  <div class="field">
    <%= f.label :s16 %><br>
    <%= f.number_field :s16 %>
  </div>
  <div class="field">
    <%= f.label :s17 %><br>
    <%= f.number_field :s17 %>
  </div>
  <div class="field">
    <%= f.label :s18 %><br>
    <%= f.number_field :s18 %>
  </div>
  <div class="field">
    <%= f.label :s19 %><br>
    <%= f.number_field :s19 %>
  </div>
  <div class="field">
    <%= f.label :s20 %><br>
    <%= f.number_field :s20 %>
  </div>
  <div class="field">
    <%= f.label :s21 %><br>
    <%= f.number_field :s21 %>
  </div>
  <div class="field">
    <%= f.label :s22 %><br>
    <%= f.number_field :s22 %>
  </div>
  <div class="field">
    <%= f.label :s23 %><br>
    <%= f.number_field :s23 %>
  </div>
  <div class="field">
    <%= f.label :s24 %><br>
    <%= f.number_field :s24 %>
  </div>
  <div class="field">
    <%= f.label :s25 %><br>
    <%= f.number_field :s25 %>
  </div>
  <div class="field">
    <%= f.label :s26 %><br>
    <%= f.number_field :s26 %>
  </div>
  <div class="field">
    <%= f.label :s27 %><br>
    <%= f.number_field :s27 %>
  </div>
  <div class="field">
    <%= f.label :s28 %><br>
    <%= f.number_field :s28 %>
  </div>
  <div class="field">
    <%= f.label :s29 %><br>
    <%= f.number_field :s29 %>
  </div>
  <div class="field">
    <%= f.label :s30 %><br>
    <%= f.number_field :s30 %>
  </div>
  <div class="field">
    <%= f.label :s31 %><br>
    <%= f.number_field :s31 %>
  </div>
  <div class="field">
    <%= f.label :s32 %><br>
    <%= f.number_field :s32 %>
  </div>
  <div class="field">
    <%= f.label :s33 %><br>
    <%= f.number_field :s33 %>
  </div>
  <div class="field">
    <%= f.label :s34 %><br>
    <%= f.number_field :s34 %>
  </div>
  <div class="field">
    <%= f.label :s35 %><br>
    <%= f.number_field :s35 %>
  </div>
  <div class="field">
    <%= f.label :s36 %><br>
    <%= f.number_field :s36 %>
  </div>
  <div class="field">
    <%= f.label :s37 %><br>
    <%= f.number_field :s37 %>
  </div>
  <div class="field">
    <%= f.label :s38 %><br>
    <%= f.number_field :s38 %>
  </div>
  <div class="field">
    <%= f.label :s39 %><br>
    <%= f.number_field :s39 %>
  </div>
  <div class="field">
    <%= f.label :s40 %><br>
    <%= f.number_field :s40 %>
  </div>
  <div class="field">
    <%= f.label :s41 %><br>
    <%= f.number_field :s41 %>
  </div>
  <div class="field">
    <%= f.label :s42 %><br>
    <%= f.number_field :s42 %>
  </div>
  <div class="field">
    <%= f.label :s43 %><br>
    <%= f.number_field :s43 %>
  </div>
  <div class="field">
    <%= f.label :s44 %><br>
    <%= f.number_field :s44 %>
  </div>
  <div class="field">
    <%= f.label :s45 %><br>
    <%= f.number_field :s45 %>
  </div>
  <div class="field">
    <%= f.label :s46 %><br>
    <%= f.number_field :s46 %>
  </div>
  <div class="field">
    <%= f.label :s47 %><br>
    <%= f.number_field :s47 %>
  </div>
  <div class="field">
    <%= f.label :s48 %><br>
    <%= f.number_field :s48 %>
  </div>
  <div class="field">
    <%= f.label :s49 %><br>
    <%= f.number_field :s49 %>
  </div>
  <div class="field">
    <%= f.label :s50 %><br>
    <%= f.number_field :s50 %>
  </div>
  <div class="field">
    <%= f.label :s51 %><br>
    <%= f.number_field :s51 %>
  </div>
  <div class="field">
    <%= f.label :s52 %><br>
    <%= f.number_field :s52 %>
  </div>
  <div class="field">
    <%= f.label :poblacion %><br>
    <%= f.number_field :poblacion %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

Plataforma/app/views/epiyears/edit.html.erb
<h1>Editing Epiyear</h1>

<%= render 'form' %>

<%= link_to 'Show', @epiyear %> |
<%= link_to 'Back', epiyears_path %>

Plataforma/app/views/epiyears/index.html.erb
<h1>Casos por semana y por Años</h1>

<table>
  <thead>
    <tr>
      <th>Año</th>
      <th>S1</th>
      <th>S2</th>
      <th>S3</th>
      <th>S4</th>
      <th>S5</th>
      <th>S6</th>
      <th>S7</th>
      <th>S8</th>
      <th>S9</th>
      <th>S10</th>
      <th>S11</th>
      <th>S12</th>
      <th>S13</th>
      <th>S14</th>
      <th>S15</th>
      <th>S16</th>
      <th>S17</th>
      <th>S18</th>
      <th>S19</th>
      <th>S20</th>
      <th>S21</th>
      <th>S22</th>
      <th>S23</th>
      <th>S24</th>
      <th>S25</th>
      <th>S26</th>
      <th>S27</th>
      <th>S28</th>
      <th>S29</th>
      <th>S30</th>
      <th>S31</th>
      <th>S32</th>
      <th>S33</th>
      <th>S34</th>
      <th>S35</th>
      <th>S36</th>
      <th>S37</th>
      <th>S38</th>
      <th>S39</th>
      <th>S40</th>
      <th>S41</th>
      <th>S42</th>
      <th>S43</th>
      <th>S44</th>
      <th>S45</th>
      <th>S46</th>
      <th>S47</th>
      <th>S48</th>
      <th>S49</th>
      <th>S50</th>
      <th>S51</th>
      <th>S52</th>
      <th>Poblacion</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @epiyears.each do |epiyear| %>
      <tr>
        <td><%= epiyear.year %></td>
        <td><%= epiyear.s1 %></td>
        <td><%= epiyear.s2 %></td>
        <td><%= epiyear.s3 %></td>
        <td><%= epiyear.s4 %></td>
        <td><%= epiyear.s5 %></td>
        <td><%= epiyear.s6 %></td>
        <td><%= epiyear.s7 %></td>
        <td><%= epiyear.s8 %></td>
        <td><%= epiyear.s9 %></td>
        <td><%= epiyear.s10 %></td>
        <td><%= epiyear.s11 %></td>
        <td><%= epiyear.s12 %></td>
        <td><%= epiyear.s13 %></td>
        <td><%= epiyear.s14 %></td>
        <td><%= epiyear.s15 %></td>
        <td><%= epiyear.s16 %></td>
        <td><%= epiyear.s17 %></td>
        <td><%= epiyear.s18 %></td>
        <td><%= epiyear.s19 %></td>
        <td><%= epiyear.s20 %></td>
        <td><%= epiyear.s21 %></td>
        <td><%= epiyear.s22 %></td>
        <td><%= epiyear.s23 %></td>
        <td><%= epiyear.s24 %></td>
        <td><%= epiyear.s25 %></td>
        <td><%= epiyear.s26 %></td>
        <td><%= epiyear.s27 %></td>
        <td><%= epiyear.s28 %></td>
        <td><%= epiyear.s29 %></td>
        <td><%= epiyear.s30 %></td>
        <td><%= epiyear.s31 %></td>
        <td><%= epiyear.s32 %></td>
        <td><%= epiyear.s33 %></td>
        <td><%= epiyear.s34 %></td>
        <td><%= epiyear.s35 %></td>
        <td><%= epiyear.s36 %></td>
        <td><%= epiyear.s37 %></td>
        <td><%= epiyear.s38 %></td>
        <td><%= epiyear.s39 %></td>
        <td><%= epiyear.s40 %></td>
        <td><%= epiyear.s41 %></td>
        <td><%= epiyear.s42 %></td>
        <td><%= epiyear.s43 %></td>
        <td><%= epiyear.s44 %></td>
        <td><%= epiyear.s45 %></td>
        <td><%= epiyear.s46 %></td>
        <td><%= epiyear.s47 %></td>
        <td><%= epiyear.s48 %></td>
        <td><%= epiyear.s49 %></td>
        <td><%= epiyear.s50 %></td>
        <td><%= epiyear.s51 %></td>
        <td><%= epiyear.s52 %></td>
        <td><%= epiyear.poblacion %></td>
        <td><%= link_to 'Show', epiyear %></td>
        <td><%= link_to 'Edit', edit_epiyear_path(epiyear) %></td>
        <td><%= link_to 'Destroy', epiyear, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Ingresar Casos', new_epiyear_path %>

<h4>Importar Casos</h4>

<%= form_tag import_epiyears_path, multipart: true do %>
  <%= file_field_tag :file %>
  <%= submit_tag "Importar" %>
<% end %>

Plataforma/app/views/epiyears/new.html.erb
<h1>Agregar Año Epidemiológico</h1>

<%= render 'form' %>

<%= link_to 'Back', epiyears_path %>

Plataforma/app/views/epiyears/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Year:</strong>
  <%= @epiyear.year %>
</p>

<p>
  <strong>S1:</strong>
  <%= @epiyear.s1 %>
</p>

<p>
  <strong>S2:</strong>
  <%= @epiyear.s2 %>
</p>

<p>
  <strong>S3:</strong>
  <%= @epiyear.s3 %>
</p>

<p>
  <strong>S4:</strong>
  <%= @epiyear.s4 %>
</p>

<p>
  <strong>S5:</strong>
  <%= @epiyear.s5 %>
</p>

<p>
  <strong>S6:</strong>
  <%= @epiyear.s6 %>
</p>

<p>
  <strong>S7:</strong>
  <%= @epiyear.s7 %>
</p>

<p>
  <strong>S8:</strong>
  <%= @epiyear.s8 %>
</p>

<p>
  <strong>S9:</strong>
  <%= @epiyear.s9 %>
</p>

<p>
  <strong>S10:</strong>
  <%= @epiyear.s10 %>
</p>

<p>
  <strong>S11:</strong>
  <%= @epiyear.s11 %>
</p>

<p>
  <strong>S12:</strong>
  <%= @epiyear.s12 %>
</p>

<p>
  <strong>S13:</strong>
  <%= @epiyear.s13 %>
</p>

<p>
  <strong>S14:</strong>
  <%= @epiyear.s14 %>
</p>

<p>
  <strong>S15:</strong>
  <%= @epiyear.s15 %>
</p>

<p>
  <strong>S16:</strong>
  <%= @epiyear.s16 %>
</p>

<p>
  <strong>S17:</strong>
  <%= @epiyear.s17 %>
</p>

<p>
  <strong>S18:</strong>
  <%= @epiyear.s18 %>
</p>

<p>
  <strong>S19:</strong>
  <%= @epiyear.s19 %>
</p>

<p>
  <strong>S20:</strong>
  <%= @epiyear.s20 %>
</p>

<p>
  <strong>S21:</strong>
  <%= @epiyear.s21 %>
</p>

<p>
  <strong>S22:</strong>
  <%= @epiyear.s22 %>
</p>

<p>
  <strong>S23:</strong>
  <%= @epiyear.s23 %>
</p>

<p>
  <strong>S24:</strong>
  <%= @epiyear.s24 %>
</p>

<p>
  <strong>S25:</strong>
  <%= @epiyear.s25 %>
</p>

<p>
  <strong>S26:</strong>
  <%= @epiyear.s26 %>
</p>

<p>
  <strong>S27:</strong>
  <%= @epiyear.s27 %>
</p>

<p>
  <strong>S28:</strong>
  <%= @epiyear.s28 %>
</p>

<p>
  <strong>S29:</strong>
  <%= @epiyear.s29 %>
</p>

<p>
  <strong>S30:</strong>
  <%= @epiyear.s30 %>
</p>

<p>
  <strong>S31:</strong>
  <%= @epiyear.s31 %>
</p>

<p>
  <strong>S32:</strong>
  <%= @epiyear.s32 %>
</p>

<p>
  <strong>S33:</strong>
  <%= @epiyear.s33 %>
</p>

<p>
  <strong>S34:</strong>
  <%= @epiyear.s34 %>
</p>

<p>
  <strong>S35:</strong>
  <%= @epiyear.s35 %>
</p>

<p>
  <strong>S36:</strong>
  <%= @epiyear.s36 %>
</p>

<p>
  <strong>S37:</strong>
  <%= @epiyear.s37 %>
</p>

<p>
  <strong>S38:</strong>
  <%= @epiyear.s38 %>
</p>

<p>
  <strong>S39:</strong>
  <%= @epiyear.s39 %>
</p>

<p>
  <strong>S40:</strong>
  <%= @epiyear.s40 %>
</p>

<p>
  <strong>S41:</strong>
  <%= @epiyear.s41 %>
</p>

<p>
  <strong>S42:</strong>
  <%= @epiyear.s42 %>
</p>

<p>
  <strong>S43:</strong>
  <%= @epiyear.s43 %>
</p>

<p>
  <strong>S44:</strong>
  <%= @epiyear.s44 %>
</p>

<p>
  <strong>S45:</strong>
  <%= @epiyear.s45 %>
</p>

<p>
  <strong>S46:</strong>
  <%= @epiyear.s46 %>
</p>

<p>
  <strong>S47:</strong>
  <%= @epiyear.s47 %>
</p>

<p>
  <strong>S48:</strong>
  <%= @epiyear.s48 %>
</p>

<p>
  <strong>S49:</strong>
  <%= @epiyear.s49 %>
</p>

<p>
  <strong>S50:</strong>
  <%= @epiyear.s50 %>
</p>

<p>
  <strong>S51:</strong>
  <%= @epiyear.s51 %>
</p>

<p>
  <strong>S52:</strong>
  <%= @epiyear.s52 %>
</p>

<p>
  <strong>Poblacion:</strong>
  <%= @epiyear.poblacion %>
</p>

<%= link_to 'Edit', edit_epiyear_path(@epiyear) %> |
<%= link_to 'Back', epiyears_path %>